### ISSUE TITLE
Updates dont merge

### ISSUE THREAD

**Issue by LUC1DDREAM** [ai8772/D4EventsTrackerOverlay#8]
Hi, i'm new on github so i forked the branch, updated the affix files for missing affixes and github said automerge is active but there was no update for the last 2-3 hours

**Comment by ai8772** [comment]
hm i don't know i allowed autot merge without having me to check confirm changes but i also didn't get any notifications from you, maybe you didn't do it right? as the owner i just have to edit the files so i'm not sure what other users must do.
Otherwise you can tell me your changes and i'll do it for you

**Comment by LUC1DDREAM** [comment]
would be good for me to figure out how to do it so i dont have to bother you every day for changes, when im stuck i'll get back to you, thanks

**Comment by ai8772** [comment]
looks like i still have to confirm, i don't know if it's possible to set it to auto but for now it's fine. I'll do it asap when i get a notification.

**Comment by LUC1DDREAM** [comment]
worry not, maybe if its not hard, you can add a function into the program to add own fork as input
